### ISSUE TITLE
Image.Clone() crashes

### ISSUE THREAD

**Issue by underscore-zi** [dram55/MarioMaker2OCR#35]
Not sure if this is related to #33.

Karibukai Play's would get application crashes when using any resolution besides 640x480

From the error log:

**720p**
```
2019-07-27 00:17:44,408 [9] DEBUG MarioMaker2OCR.VideoProcessor - Found resolution: 1280x720 with 3 channels.
2019-07-27 00:18:12,144 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-27 00:18:13,753 [9] INFO MarioMaker2OCR.Form1 - Detected exit.
2019-07-27 00:19:03,067 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-27 00:19:08,865 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-27 00:19:08,882 [9] INFO MarioMaker2OCR.Form1 - Detected new level.
2019-07-27 00:19:09,344 [9] DEBUG MarioMaker2OCR.OCRLibrary - level: 5QM-FRB-W8G
2019-07-27 00:20:28,802 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-27 00:21:35,920 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-27 00:21:45,736 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-27 00:21:57,870 [9] DEBUG MarioMaker2OCR.Form1 - Detected Level Clear
2019-07-27 00:22:07,767 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-27 00:22:09,348 [9] INFO MarioMaker2OCR.Form1 - Detected exit.
2019-07-27 00:22:09,352 [8] DEBUG MarioMaker2OCR.VideoProcessor - Error in frame buffer tick
2019-07-27 00:22:09,352 [8] ERROR MarioMaker2OCR.VideoProcessor - Emgu.CV.Util.CvException: OpenCV: 
   at Emgu.CV.CvInvoke.CvErrorHandler(Int32 status, IntPtr funcName, IntPtr errMsg, IntPtr fileName, Int32 line, IntPtr userData)
   at Emgu.CV.CvInvoke.cvSetImageCOI(IntPtr image, Int32 coi)
   at Emgu.CV.Image`2.Clone()
   at MarioMaker2OCR.VideoProcessor.frameBuffer_tick(Object sender)
```

**1080**
```
2019-07-26 23:13:20,720 [9] DEBUG MarioMaker2OCR.VideoProcessor - Found resolution: 1920x1080 with 3 channels.
2019-07-26 23:13:23,988 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-26 23:13:25,386 [9] INFO MarioMaker2OCR.Form1 - Detected death.
2019-07-26 23:13:32,248 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-26 23:13:33,691 [9] INFO MarioMaker2OCR.Form1 - Detected death.
2019-07-26 23:13:42,821 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-26 23:13:44,202 [9] INFO MarioMaker2OCR.Form1 - Detected death.
2019-07-26 23:14:01,041 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-26 23:14:16,740 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-26 23:14:28,580 [9] DEBUG MarioMaker2OCR.VideoProcessor - Exception in main procesisng loop
2019-07-26 23:14:28,580 [9] ERROR MarioMaker2OCR.VideoProcessor - Emgu.CV.Util.CvException: OpenCV: 
   at Emgu.CV.CvInvoke.CvErrorHandler(Int32 status, IntPtr funcName, IntPtr errMsg, IntPtr fileName, Int32 line, IntPtr userData)
   at Emgu.CV.CvInvoke.cvSetImageCOI(IntPtr image, Int32 coi)
   at Emgu.CV.Image`2.Clone()
   at MarioMaker2OCR.VideoProcessor.copyFrameBuffer()
   at MarioMaker2OCR.VideoProcessor.processingLoop()
```

Also one crash in framebuffer_tick on 480

```
2019-07-26 23:53:34,184 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-26 23:54:31,908 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-26 23:55:11,374 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-26 23:55:25,274 [9] DEBUG MarioMaker2OCR.Form1 - Detected a black screen
2019-07-26 23:55:27,551 [16] DEBUG MarioMaker2OCR.VideoProcessor - Error in frame buffer tick
2019-07-26 23:55:27,551 [16] ERROR MarioMaker2OCR.VideoProcessor - Emgu.CV.Util.CvException: OpenCV: src.depth() == dst.depth() && src.size == dst.size
   at Emgu.CV.CvInvoke.CvErrorHandler(Int32 status, IntPtr funcName, IntPtr errMsg, IntPtr fileName, Int32 line, IntPtr userData)
   at Emgu.CV.CvInvoke.cvCopy(IntPtr src, IntPtr des, IntPtr mask)
   at Emgu.CV.Image`2.Copy(Image`2 dest, Image`2 mask)
   at Emgu.CV.Image`2.Copy(Image`2 mask)
   at Emgu.CV.Image`2.Clone()
   at MarioMaker2OCR.VideoProcessor.frameBuffer_tick(Object sender)
```

**Comment by underscore-zi** [comment]
[MarioMaker2OCR.log](https://github.com/dram55/MarioMaker2OCR/files/3438850/MarioMaker2OCR.log)

**Comment by dram55** [comment]
While leaving the program running in the background I just got the Emgu.CV.Util.CvException: OpenCV: src.depth() == dst.depth() && src.size == dst.size flavor of the exception in copyFrameBuffer().

I verified that the frame in the buffer we were trying to copy had a depth of 3 and size of 720, 1280 - which was the same as every other frame in the buffer. This confused me, I thought maybe a null frame or maybe a Gray frame was somehow slipping through. 

Either way - I will add some exception handling in copyFrameBuffer(), since it's executed on it's own thread it is causing the program to crash.

```
   at Emgu.CV.CvInvoke.CvErrorHandler(Int32 status, IntPtr funcName, IntPtr errMsg, IntPtr fileName, Int32 line, IntPtr userData)
   at Emgu.CV.CvInvoke.cvCopy(IntPtr src, IntPtr des, IntPtr mask)
   at Emgu.CV.Image`2.Copy(Image`2 dest, Image`2 mask)
   at Emgu.CV.Image`2.Copy(Image`2 mask)
   at Emgu.CV.Image`2.Clone()
   at MarioMaker2OCR.VideoProcessor.copyFrameBuffer() in C:\Users\Jon\source\repos\EmguCV Projects\MarioMaker2OCR\MarioMaker2OCR\VideoProcessor.cs:line 510
   at MarioMaker2OCR.VideoProcessor.onBlackScreenStart() in C:\Users\Jon\source\repos\EmguCV Projects\MarioMaker2OCR\MarioMaker2OCR\VideoProcessor.cs:line 588
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
