### ISSUE TITLE
Application Crash after clicking Start

### ISSUE THREAD

**Issue by dj-modo** [dram55/MarioMaker2OCR#57]
haven't managed to get this program to run correctly since downloading,
i hit the start button then pops up the message 
![fault](https://user-images.githubusercontent.com/49617291/78710465-4fe27b80-790d-11ea-826f-19d160ab49e6.PNG)

heres the log:

2020-04-07 20:16:29,306 [1] INFO MarioMaker2OCR.Form1 - Start Application - version: 1.0.69
2020-04-07 20:16:31,487 [1] INFO MarioMaker2OCR.Form1 - Start Web Server on http://localhost:3000/
2020-04-07 20:16:31,588 [1] ERROR MarioMaker2OCR.Form1 - Error starting video device: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
2020-04-07 20:16:31,591 [1] DEBUG MarioMaker2OCR.Form1 -    at Emgu.CV.CvInvoke.cveVideoCaptureCreateFromDevice(Int32 index, API apiPreference)
   at Emgu.CV.VideoCapture..ctor(Int32 camIndex, API captureApi)
   at MarioMaker2OCR.VideoProcessor.createCaptureDevice(Int32 device, Size captureResolution)
   at MarioMaker2OCR.VideoProcessor..ctor(Int32 device, Size resolution)
   at MarioMaker2OCR.Form1.startButton_Click(Object sender, EventArgs e)

my OP system is win 10 1903 enterprise N 64bit

let me know if you need any more info cheers

**Comment by dj-modo** [comment]
managed to resolve the issue, because my system is windows "N" this is a version that doesn't have windows media player installed, i discovered that the ocr program requires the media player version as it uses some of it's relative files as dependencies, i had to install the media feature pack for window N versions to get the required files, once the media feature pack was installed (downloaded from Microsoft's website) the ocr program started working as intended
![yaaassssssss](https://user-images.githubusercontent.com/49617291/78745787-120d4380-795d-11ea-8c2d-c77ffa9f6d52.PNG)

**Comment by dram55** [comment]
Hey @dj-modo thanks for figuring this out! I didn't get a chance to look at it. 

I will add this to our readme

**Comment by Super-JoConnell** [comment]
i've changed over my user name to my streaming alias as i'm a retired dj and don't go by dj-modo anymore if you'r wondering why the name change
